# The URL the site will be built for
base_url = "https://trosi.github.io"

# The site title and description; used in feeds by default.
title = "Tommaso Rosi"
description = "Personal blog and website"

# The default language; used in feeds.
default_language = "en"

# Set theme
theme = "emily_zola_theme"

# For overriding the default output directory `public`, set it to another value (e.g.: "docs")
output_dir = "docs"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# The default author for pages
author = "Tommaso Rosi"

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

# Define taxonomies to be rendered
taxonomies = [
    {name = "categories", rss = false},
    {name = "tags", rss = false},
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

# The theme to use for code highlighting.
# See Zola docs for list of allowed values.
highlight_theme = "base16-ocean-dark"

# When set to "true", emoji aliases translated to their corresponding
# Unicode emoji equivalent in the rendered Markdown files. (e.g.: :smile: => ğŸ˜„)
render_emoji = true

# Whether external links are to be opened in a new tab
# If this is true, a `rel="noopener"` will always automatically be added for security reasons
external_links_target_blank = true

# Whether smart punctuation is enabled (changing quotes, dashes, dots in their typographic form)
# For example, `...` into `â€¦`, `"quote"` into `â€œcurlyâ€` etc
smart_punctuation = false

# Whether to set decoding="async" and loading="lazy" for all images
# When turned on, the alt text must be plain text.
# For example, `![xx](...)` is ok but `![*x*x](...)` isnâ€™t ok
lazy_async_image = false

# Whether footnotes are rendered in the GitHub-style (at the bottom, with back references) or plain (in the place, where they are defined)
bottom_footnotes = false

[extra]
# Put all your custom variables here
